name: C/C++ CI

on:
  push:
    branches: [ "vascc" ]
  pull_request:
    branches: [ "vascc" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake_configure
      run: cmake -Bbuild .
    - name: build
      run: cmake --build ./build
    - name: run
      run: ./cc testcase/test.txt
    - name: xmake_build
      run: xmake build
    - name: xmake_run
      run: xmake run cc testcase/test.txt
